CREATE TABLE [dbo].[TBL_DETAILS_BILL] (
    [DET_BIL_INT_ID] UNIQUEIDENTIFIER NOT NULL,
    [BIL_INT_ID]     UNIQUEIDENTIFIER NOT NULL,
    [PRO_INT_ID]     UNIQUEIDENTIFIER NOT NULL,
    [DET_BIL_CAT]    INT              NOT NULL,
    [DET_BIL_PRICE]  DECIMAL (18, 2)  NOT NULL,
    [DET_BIL_DATE]   DATE             NOT NULL,
    PRIMARY KEY CLUSTERED ([DET_BIL_INT_ID] ASC),
    CONSTRAINT [FK_TBL_DETAILS_BILL_TBL_BILL] FOREIGN KEY ([BIL_INT_ID]) REFERENCES [dbo].[TBL_BILL] ([BIL_INT_ID]),
    CONSTRAINT [FK_TBL_DETAILS_BILL_TBL_PRODUCT] FOREIGN KEY ([PRO_INT_ID]) REFERENCES [dbo].[TBL_PRODUCT] ([PRO_INT_ID])
);

