CREATE TABLE [dbo].[TBL_TYPE_USER] (
    [TYP_USER_INT_ID] UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [TYP_NAME]        NVARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([TYP_USER_INT_ID] ASC)
);

