CREATE TABLE [dbo].[TBL_USER_INFO] (
    [USER_INF_INT_ID]    UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [TYP_USER_INT_ID]    UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USER_INF_PRIMER_N]  VARCHAR (100)    NULL,
    [USER_INF_SEGUNDO_N] VARCHAR (100)    NULL,
    [USER_INF_PRIMER_A]  VARCHAR (50)     NULL,
    [USER_INF_SEGUNDO_A] VARCHAR (50)     NULL,
    [USER_INF_FECHA_NAC] DATETIME         NULL,
    [USER_INF_CED]       VARCHAR (50)     NULL,
    [USER_INF_TEL]       VARCHAR (50)     NULL,
    [USER_INF_EMAIL]     VARCHAR (100)    NULL,
    PRIMARY KEY CLUSTERED ([USER_INF_INT_ID] ASC),
    CONSTRAINT [FK_TBL_USER_INFO_CAT_TYPE_USER] FOREIGN KEY ([TYP_USER_INT_ID]) REFERENCES [dbo].[TBL_TYPE_USER] ([TYP_USER_INT_ID])
);

