CREATE TABLE [dbo].[TBL_BILL] (
    [BIL_INT_ID]     UNIQUEIDENTIFIER NOT NULL,
    [TYP_PAY_INT_ID] UNIQUEIDENTIFIER NOT NULL,
    [BIL_NUMBER]     VARCHAR (MAX)    NOT NULL,
    [BIL_DATE]       DATE             NOT NULL,
    [BIL_SUBTOTAL]   DECIMAL (18, 2)  NOT NULL,
    [BIL_TOTAL]      DECIMAL (18, 2)  NOT NULL,
    [BIL_IVA]        DECIMAL (18, 2)  NULL,
    PRIMARY KEY CLUSTERED ([BIL_INT_ID] ASC),
    CONSTRAINT [FK_TBL_BILL_TBL_TYPE_PAYMENT] FOREIGN KEY ([TYP_PAY_INT_ID]) REFERENCES [dbo].[TBL_TYPE_PAYMENT] ([TYP_PAY_INT_ID])
);

