CREATE TABLE [dbo].[TBL_PRESENTATION] (
    [PRES_ID]   UNIQUEIDENTIFIER NOT NULL,
    [PRES_NAME] VARCHAR (100)    NOT NULL,
    CONSTRAINT [PK_TBL_PRESENTATION] PRIMARY KEY CLUSTERED ([PRES_ID] ASC)
);

