CREATE TABLE [dbo].[TBL_HIS_USER_AGENCY_BOX] (
    [HIS_USER_AGENCY_BOX_ID]             UNIQUEIDENTIFIER NULL,
    [USE_INT_ID]                         UNIQUEIDENTIFIER NULL,
    [BOX_INT_ID]                         UNIQUEIDENTIFIER NULL,
    [HIS_USER_AGENCY_BOX_CREATE_DATE]    DATE             NOT NULL,
    [HIS_USER_AGENCY_BOX_DISABLE_DATE]   DATE             NULL,
    [HIS_USER_AGENCY_BOX_INITIAL_AMOUNT] DECIMAL (18, 2)  NULL,
    [HIS_USER_AGENCY_BOX_BALANCE]        DECIMAL (18, 2)  NULL,
    [HIS_USER_AGENCY_BOX_EGRESS]         DECIMAL (18, 2)  NULL,
    [HIS_USER_AGENCY_BOX_DIFERENCE]      DECIMAL (18, 2)  NULL,
    CONSTRAINT [FK_TBL_HIS_USER_AGENCY_BOX_TBL_AGENCY_BOX] FOREIGN KEY ([BOX_INT_ID]) REFERENCES [dbo].[TBL_AGENCY_BOX] ([BOX_INT_ID]),
    CONSTRAINT [FK_TBL_HIS_USER_AGENCY_BOX_TBL_USER] FOREIGN KEY ([USE_INT_ID]) REFERENCES [dbo].[TBL_USER] ([USE_INT_ID])
);



