CREATE TABLE [dbo].[TBL_AGENCY_BOX] (
    [BOX_INT_ID] UNIQUEIDENTIFIER NOT NULL,
    [BOX_NAME]   VARCHAR (100)    NOT NULL,
    [BOX_STATUS] BIT              NOT NULL,
    CONSTRAINT [PK_TBL_AGENCY_BOX] PRIMARY KEY CLUSTERED ([BOX_INT_ID] ASC)
);

