CREATE TABLE [dbo].[TBL_USER] (
    [USE_INT_ID] UNIQUEIDENTIFIER CONSTRAINT [DF__TBL_USER__USER_I__59063A47] DEFAULT (newid()) NOT NULL,
    [USE_NAME]   VARCHAR (100)    NULL,
    [USE_LOGIN]  VARCHAR (100)    NULL,
    [USE_PASS]   VARCHAR (300)    NULL,
    [ROL_INT_ID] UNIQUEIDENTIFIER CONSTRAINT [DF__TBL_USER__ROL_IN__5AEE82B9] DEFAULT (newid()) NOT NULL,
    [USE_STATUS] BIT              NULL,
    CONSTRAINT [PK__TBL_USER__50A117AEB38F3E59] PRIMARY KEY CLUSTERED ([USE_INT_ID] ASC),
    CONSTRAINT [FK_TBL_USER_CAT_ROLE] FOREIGN KEY ([ROL_INT_ID]) REFERENCES [dbo].[TBL_ROLE] ([ROL_INT_ID])
);





