CREATE TABLE [dbo].[TBL_USER] (
    [USER_INT_ID]     UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USER_INF_INT_ID] UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USER_NAME]       VARCHAR (100)    NULL,
    [USER_LOGIN]      VARCHAR (100)    NULL,
    [USER_PASS]       VARCHAR (300)    NULL,
    [ROL_INT_ID]      UNIQUEIDENTIFIER DEFAULT (newid()) NULL,
    [USER_STATUS]     BIT              NULL,
    PRIMARY KEY CLUSTERED ([USER_INT_ID] ASC),
    CONSTRAINT [FK_TBL_USER_CAT_ROLE] FOREIGN KEY ([ROL_INT_ID]) REFERENCES [dbo].[TBL_ROLE] ([ROL_INT_ID]),
    CONSTRAINT [FK_TBL_USER_TBL_USER_INFO] FOREIGN KEY ([USER_INF_INT_ID]) REFERENCES [dbo].[TBL_USER_INFO] ([USER_INF_INT_ID])
);

