CREATE TABLE [dbo].[TBL_SALES_DETAILS] (
    [SAL_DET_ID]       UNIQUEIDENTIFIER NOT NULL,
    [SAL_ID]           UNIQUEIDENTIFIER NOT NULL,
    [PRO_INT_ID]       UNIQUEIDENTIFIER NOT NULL,
    [SAL_DET_QUANTITY] INT              NOT NULL,
    [SAL_DET_PRICE]    DECIMAL (18, 2)  NULL,
    CONSTRAINT [PK_TBL_SALES_DETAILS] PRIMARY KEY CLUSTERED ([SAL_DET_ID] ASC),
    CONSTRAINT [FK_TBL_SALES_DETAILS_TBL_PRODUCT] FOREIGN KEY ([SAL_ID]) REFERENCES [dbo].[TBL_PRODUCT] ([PRO_INT_ID]),
    CONSTRAINT [FK_TBL_SALES_DETAILS_TBL_SALES] FOREIGN KEY ([SAL_ID]) REFERENCES [dbo].[TBL_SALES] ([SAL_ID])
);



