CREATE TABLE [dbo].[TBL_KARDEX] (
    [KAR_ID]              UNIQUEIDENTIFIER NOT NULL,
    [PRO_INT_ID]          UNIQUEIDENTIFIER NOT NULL,
    [TYP_KAR_ID]          UNIQUEIDENTIFIER NOT NULL,
    [KAR_DECRIPTION]      VARCHAR (MAX)    NOT NULL,
    [KAR_CREATE_DATE]     DATETIME         NOT NULL,
    [KAR_PRICE_BUY]       DECIMAL (18, 2)  NOT NULL,
    [KAR_QUANTITY]        INT              NOT NULL,
    [KAR_QUANTITY_T]      INT              NULL,
    [KAR_EXPIRATION_DATE] DATE             NOT NULL,
    [KAR_DISABLE_DATE]    DATETIME         NULL,
    CONSTRAINT [PK_TBL_KARDEX] PRIMARY KEY CLUSTERED ([KAR_ID] ASC),
    CONSTRAINT [FK_TBL_KARDEX_TBL_PRODUCT] FOREIGN KEY ([PRO_INT_ID]) REFERENCES [dbo].[TBL_PRODUCT] ([PRO_INT_ID]),
    CONSTRAINT [FK_TBL_KARDEX_TBL_TYPE_KARDEX] FOREIGN KEY ([TYP_KAR_ID]) REFERENCES [dbo].[TBL_TYPE_KARDEX] ([TYP_KAR_ID])
);






GO
CREATE TRIGGER [dbo].[TR_PRODUCT]
ON dbo.TBL_KARDEX
AFTER  INSERT 
AS 
BEGIN
SET NOCOUNT ON;
UPDATE P
SET P.PRO_STOCK = ISNULL(P.PRO_STOCK, 0) + K.KAR_QUANTITY
FROM TBL_PRODUCT P
INNER JOIN INSERTED K ON P.PRO_INT_ID = K.PRO_INT_ID
END
GO
CREATE TRIGGER [dbo].[TR_PRODUCT_UPDATE]
ON [dbo].[TBL_KARDEX]
AFTER UPDATE 
AS 
BEGIN
SET NOCOUNT ON;
	UPDATE P
	SET P.PRO_STOCK = (SELECT SUM(KAR_QUANTITY) FROM TBL_KARDEX WHERE PRO_INT_ID = (SELECT PRO_INT_ID FROM TBL_PRODUCT WHERE PRO_NAME='Testts') AND TYP_KAR_ID = (SELECT TYP_KAR_ID FROM TBL_TYPE_KARDEX WHERE TYP_KAR_NAME = 'Entrada') AND KAR_DISABLE_DATE IS NULL)
	FROM TBL_PRODUCT P
	INNER JOIN INSERTED K ON P.PRO_INT_ID = K.PRO_INT_ID
END