CREATE TABLE [dbo].[TBL_CATEGORY] (
    [CAT_INT_ID]   UNIQUEIDENTIFIER CONSTRAINT [DF_CAT_CATEGORIA_CAT_INT_ID] DEFAULT (newid()) NOT NULL,
    [CAT_NOMBRE]   VARCHAR (50)     NULL,
    [CAT_SYS_NAME] VARCHAR (50)     NULL,
    [CAT_STATUS]   BIT              NULL,
    PRIMARY KEY CLUSTERED ([CAT_INT_ID] ASC)
);

