CREATE TABLE [dbo].[TBL_KARDEX] (
    [KAR_ID]              UNIQUEIDENTIFIER NOT NULL,
    [PRO_INT_ID]          UNIQUEIDENTIFIER NOT NULL,
    [TYP_KAR_ID]          UNIQUEIDENTIFIER NOT NULL,
    [KAR_DECRIPTION]      VARCHAR (MAX)    NOT NULL,
    [KAR_CREATE_DATE]     DATETIME         NOT NULL,
    [KAR_PRICE_BUY]       DECIMAL (18, 2)  NOT NULL,
    [KAR_QUANTITY]        INT              NOT NULL,
    [KAR_EXPIRATION_DATE] DATE             NOT NULL,
    CONSTRAINT [FK_TBL_KARDEX_TBL_PRODUCT] FOREIGN KEY ([PRO_INT_ID]) REFERENCES [dbo].[TBL_PRODUCT] ([PRO_INT_ID]),
    CONSTRAINT [FK_TBL_KARDEX_TBL_TYPE_KARDEX] FOREIGN KEY ([TYP_KAR_ID]) REFERENCES [dbo].[TBL_TYPE_KARDEX] ([TYP_KAR_ID])
);

