CREATE TABLE [dbo].[TBL_TYPE_KARDEX] (
    [TYP_KAR_ID]    UNIQUEIDENTIFIER NOT NULL,
    [TYP_KAR_NAME]  VARCHAR (100)    NOT NULL,
    [TYP_KAR_ORDER] INT              NULL,
    CONSTRAINT [PK_TBL_TYPE_KARDEX] PRIMARY KEY CLUSTERED ([TYP_KAR_ID] ASC)
);

