CREATE TABLE [dbo].[TBL_INVOICE] (
    [INV_INT_ID]     UNIQUEIDENTIFIER NOT NULL,
    [SAL_ID]         UNIQUEIDENTIFIER NOT NULL,
    [TYP_PAY_INT_ID] UNIQUEIDENTIFIER NOT NULL,
    [INV_NUMBER]     VARCHAR (MAX)    NOT NULL,
    [INV_DATE]       DATETIME         NOT NULL,
    [INV_SUBTOTAL]   DECIMAL (18, 2)  NOT NULL,
    [INV_TOTAL]      DECIMAL (18, 2)  NOT NULL,
    [INV_IVA]        DECIMAL (18, 2)  NULL,
    CONSTRAINT [PK__TBL_BILL__215475377D7020CF] PRIMARY KEY CLUSTERED ([INV_INT_ID] ASC),
    CONSTRAINT [FK_TBL_BILL_TBL_TYPE_PAYMENT] FOREIGN KEY ([TYP_PAY_INT_ID]) REFERENCES [dbo].[TBL_TYPE_PAYMENT] ([TYP_PAY_INT_ID]),
    CONSTRAINT [FK_TBL_INVOICE_TBL_SALES1] FOREIGN KEY ([SAL_ID]) REFERENCES [dbo].[TBL_SALES] ([SAL_ID])
);



