CREATE PROCEDURE GET_PRODUCT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PR.PRO_INT_ID, PR.CAT_INT_ID, PR.PRO_NAME AS Nombre, PR.PRO_CODE AS Código, PR.PRO_STOCK AS Cantidad, PR.PRO_PRICE_SALES, PR.PRO_STATUS AS Estado FROM  TBL_PRODUCT PR
END