CREATE PROCEDURE [dbo].[GET_PRODUCT_KARDEX]
 @prodIntId UNIQUEIDENTIFIER,
 @typKardex UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT KD.KAR_ID, KD.KAR_DECRIPTION AS Descripción , KD.KAR_PRICE_BUY,
		   KD.KAR_QUANTITY AS Cantidad, KD.KAR_CREATE_DATE,  KD.KAR_EXPIRATION_DATE
	FROM  TBL_KARDEX KD INNER JOIN  TBL_PRODUCT PR  ON PR.PRO_INT_ID = KD.PRO_INT_ID
	WHERE KD.PRO_INT_ID = @prodIntId AND KD.TYP_KAR_ID = @typKardex AND KD.KAR_DISABLE_DATE IS NULL
	ORDER BY KD.KAR_CREATE_DATE ASC
END