
CREATE PROCEDURE INSERT_ROLE
    @ROL_INT_ID UNIQUEIDENTIFIER,
    @ROL_NAME VARCHAR(100)

AS

BEGIN
    IF NOT EXISTS (SELECT * FROM TBL_ROLE WHERE ROL_INT_ID = @ROL_INT_ID)
    BEGIN
        INSERT INTO TBL_ROLE VALUES (@ROL_INT_ID, @ROL_NAME)
    END
    ELSE
    BEGIN
        UPDATE TBL_ROLE SET ROL_NAME = @ROL_NAME
        WHERE ROL_INT_ID = @ROL_INT_ID
    END
END
