CREATE PROCEDURE SP_GET_USER

AS
BEGIN
	SET NOCOUNT ON;

	SELECT US.USE_INT_ID, US.ROL_INT_ID, US.USE_NAME AS Nombre, US.USE_LOGIN AS Usuario,
		   US.USE_PASS AS Contraseña, RL.ROL_NAME AS Rol, US.USE_STATUS AS Estado
	FROM TBL_USER US INNER JOIN TBL_ROLE RL ON US.ROL_INT_ID = RL.ROL_INT_ID
END