
CREATE PROCEDURE [dbo].[SP_GET_HIS_AGENCY_BOX_BY_USER_ID](
   @useIntId   UNIQUEIDENTIFIER	
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM TBL_HIS_USER_AGENCY_BOX WHERE USE_INT_ID = @useIntId AND HIS_USER_AGENCY_BOX_DISABLE_DATE IS NULL
END